SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS monitoring_surat;
DROP TABLE IF EXISTS surat_masuk;
DROP TABLE IF EXISTS approval_surat;
DROP TABLE IF EXISTS surat_keluar;
DROP TABLE IF EXISTS parameter_surat;
DROP TABLE IF EXISTS template_surat;
DROP TABLE IF EXISTS config_nomor_surat;
DROP TABLE IF EXISTS master_takah;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE users (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
role VARCHAR(20) NOT NULL DEFAULT 'user',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE master_takah (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
code VARCHAR(20) NOT NULL UNIQUE,
name VARCHAR(100) NOT NULL,
description TEXT,
sort_order INT DEFAULT 0,
created_by BIGINT NULL,
updated_by BIGINT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_master_takah_created_by
FOREIGN KEY (created_by) REFERENCES users(id)
ON DELETE SET NULL ON UPDATE CASCADE,
CONSTRAINT fk_master_takah_updated_by
FOREIGN KEY (updated_by) REFERENCES users(id)
ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE config_nomor_surat (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
takah_id BIGINT NOT NULL,
company_code VARCHAR(50) NOT NULL,
division_code VARCHAR(50) NULL,
reset_type VARCHAR(20) NOT NULL DEFAULT 'monthly',
last_number INT NOT NULL DEFAULT 0,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_config_nomor_surat_takah
FOREIGN KEY (takah_id) REFERENCES master_takah(id)
ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE template_surat (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
takah_id BIGINT NOT NULL,
template_name VARCHAR(150) NOT NULL,
content TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_template_surat_takah
FOREIGN KEY (takah_id) REFERENCES master_takah(id)
ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE parameter_surat (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
template_id BIGINT NOT NULL,
parameter_name VARCHAR(100) NOT NULL,
parameter_key VARCHAR(100) NOT NULL,
input_type VARCHAR(30) NOT NULL DEFAULT 'text',
is_required BOOLEAN NOT NULL DEFAULT TRUE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_parameter_surat_template
FOREIGN KEY (template_id) REFERENCES template_surat(id)
ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE surat_keluar (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nomor_surat VARCHAR(100) NOT NULL UNIQUE,
takah_id BIGINT NOT NULL,
tujuan_surat VARCHAR(150) NOT NULL,
perihal VARCHAR(150) NOT NULL,
lampiran VARCHAR(150) NULL,
tanggal_surat DATE NOT NULL,
file_surat VARCHAR(255) NULL,
status VARCHAR(30) NOT NULL DEFAULT 'draft',
created_by BIGINT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_surat_keluar_takah
FOREIGN KEY (takah_id) REFERENCES master_takah(id)
ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_surat_keluar_created_by
FOREIGN KEY (created_by) REFERENCES users(id)
ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE approval_surat (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
surat_keluar_id BIGINT NOT NULL,
approver_id BIGINT NULL,
approver_name VARCHAR(100) NOT NULL,
approval_status VARCHAR(30) NOT NULL DEFAULT 'pending',
notes TEXT,
approved_at TIMESTAMP NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_approval_surat_keluar
FOREIGN KEY (surat_keluar_id) REFERENCES surat_keluar(id)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_approval_approver
FOREIGN KEY (approver_id) REFERENCES users(id)
ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE surat_masuk (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nomor_surat VARCHAR(100) NOT NULL,
pengirim VARCHAR(150) NOT NULL,
penerima VARCHAR(150) NOT NULL,
perihal VARCHAR(150) NOT NULL,
file_surat VARCHAR(255) NULL,
tanggal_surat DATE NOT NULL,
keterangan TEXT,
status VARCHAR(30) NOT NULL DEFAULT 'received',
created_by BIGINT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_surat_masuk_created_by
FOREIGN KEY (created_by) REFERENCES users(id)
ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE monitoring_surat (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
surat_keluar_id BIGINT NULL,
surat_masuk_id BIGINT NULL,
nomor_surat VARCHAR(100) NOT NULL,
status VARCHAR(30) NOT NULL,
last_approver VARCHAR(100) NULL,
last_notes TEXT,
updated_by BIGINT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_monitoring_surat_keluar
FOREIGN KEY (surat_keluar_id) REFERENCES surat_keluar(id)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_monitoring_surat_masuk
FOREIGN KEY (surat_masuk_id) REFERENCES surat_masuk(id)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_monitoring_updated_by
FOREIGN KEY (updated_by) REFERENCES users(id)
ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;
